application:
  name: drive-core

server:
  port: 8086

spring:
  profiles:
    active: dev

datasource:
  url: jdbc:mariadb://127.0.0.1:3306/drive?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
  driver: org.mariadb.jdbc.Driver
  username: root
  password: 12345678

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: 12345678
  timeout: 50000
  connect-timeout: 10000
  jedis:
    pool:
      max-active: 20
      max-wait: 5000
      max-idle: 10
      min-idle: 0

wxteacher:
  appid: appid
  secret: secret

wxstudent:
  appid: appid
  secret: secret

caffeine:
  cache-names: [cachea]
  spec: initialCapacity=50,maximumSize=500,expireAfterAccess=5m

nginx:
  path: /Users/guiyan/workspace/ngwww/driveupload

rabbitmq:
  host: 127.0.0.1
  port: 5672
  virtualHost: "/"
  username: root
  password: 12345678
